@echo off
PYTHON C:\VICTUS\ENTERTANMENT\01_CONTROL\ORGANIZER.PY
PYTHON C:\VICTUS\ENTERTANMENT\01_CONTROL\POSTER.PY
PYTHON C:\VICTUS\ENTERTANMENT\01_CONTROL\METADATA.PY
PYTHON C:\VICTUS\ENTERTANMENT\01_CONTROL\HISTORY.PY
pause